config/routes.rb
Rails.application.routes.draw do
  get '/'=> 'coins#index'
  get '/coins' => 'coins#index'
  get '/coins/print' => 'coins#print', as: :print_coins
  get '/coins/new' => 'coins#new', as: :new_coin
  get '/coins/:id' => 'coins#edit', as: :coin
  get '/coins/:id/edit' => 'coins#edit', as: :edit_coin
  get '/coins/:id/duplicate' => 'coins#duplicate', as: :duplicate_coin
  delete '/coins/clear' => 'coins#clear', as: :clear_coins
  post '/coins' => 'coins#create'
  patch '/coins/:id' => 'coins#update'
  delete '/coins/:id/delete' => 'coins#destroy', as: :delete_coin
  post '/coins/new/fastinput' => 'coins#fastinput', as: :fastinput_coin
  

end

app/models/coin.rb
class Coin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index 
    @coins = Coin.all
  end
  
  
  def print
    @coins = Coin.all
    
    @qrcodes = Array.new
    
    for index in 0 ... @coins.size
      @qrcodes[index] = generateQrCode(@coins[index])
    end
    
  end
  def new
    @coin = Coin.new
  end
  def edit
    @coin = Coin.find(params[:id])
    @img = generateQrCode(@coin)
  end
  def duplicate
    old_coin = Coin.find(params[:id])
    new_coin = old_coin.dup
    
    if new_coin.save
      redirect_to '/coins'
    end
  end
  def create 
    @coin = Coin.new(coin_params) 
    if @coin.save 
      redirect_to coin_path(@coin)
    else 
      render 'new' 
    end 
  end
  def update
    @coin = Coin.find(params[:id])
    if @coin.update(coin_params)
      @coin = Coin.find(params[:id])
      redirect_to coin_path(@coin)
    end
  end
  def destroy
    @coin = Coin.find(params[:id])
    if @coin.destroy
      redirect_to coins_path
    end
  end
  def clear
    Coin.delete_all
    redirect_to coins_path
  end
  def fastinput
    @coin = Coin.new(coin_params)
    
    lines = @coin.fastinput.split("\n")
    
    lines.each { |l|
      value = getvalue("Years", l)
      if (value == nil)
        value = getvalue("Year", l)
        if (value != nil)
          @coin.date = value
        end
      end
      
      value = getvalue("Country", l)
      if (value != nil)
        @coin.country = value
      end
      
      value = getvalue("Metal", l)
      if (value != nil)
        @coin.composition = value
      end
      
      value = getvalue("References", l)
      if (value != nil)
        @coin.catalog_no = value.delete("#")
      end
      
      value = getvalue("Value", l)
      if (value != nil)
        bracketindex = value.index("(")
        if (bracketindex == nil) 
          @coin.denomination = value
        else
          @coin.denomination = value[0, value.index("(")]
        end
      end
      
      value = getvalue("Metal", l)
      if (value != nil)
        @coin.composition = value
      end
      
      value = getvalue("Weight", l)
      if (value != nil)
        @coin.mass = value
      end
      
      value = getvalue("Diameter", l)
      if (value != nil)
        @coin.diameter = value
      end
      
      value = getvalue("Thickness", l)
      if (value != nil)
        @coin.thickness = value
      end
      
      value = getvalue("Shape", l)
      if (value != nil)
        @coin.shape = value
      end
      
      value = getvalue("Orientation", l)
      if (value != nil)
        @coin.orientation = value
      end
    }
    
    #save coin
    if @coin.save 
      redirect_to coin_path(@coin)
    else 
      render 'new' 
    end 
  end
private 
  def coin_params 
    params.require(:coin).permit(:content,
      :country,
      :date,
      :denomination,
      :grade,
      :notes,
      :condition_notes,
      :mintage,
      :catalog_no,
      :other_notes,
      :diameter,
      :composition,
      :mass,
      :thickness,
      :shape,
      :orientation,
      :qrcode,
      :fastinput)
  end
  
  def generateQrCode(coin)
    toencode = ""
    
    toencode = stringBuilder(toencode, "", coin.country)
    #toencode = stringBuilder(toencode, "", coin.denomination)
    toencode = stringBuilder(toencode, "", coin.date)
    toencode = stringBuilder(toencode, "", coin.notes)
    #toencode = stringBuilder(toencode, "Mintage", coin.mintage)
    #toencode = stringBuilder(toencode, "", coin.grade)
    #toencode = stringBuilder(toencode, "", coin.condition_notes)
    toencode = stringBuilder(toencode, "", coin.catalog_no)
    toencode = stringBuilder(toencode, "", coin.grade)
    #toencode = stringBuilder(toencode, "Diameter", coin.diameter)
    #toencode = stringBuilder(toencode, "Thickness", coin.thickness)
    #toencode = stringBuilder(toencode, "Shape", coin.shape)
    #toencode = stringBuilder(toencode, "Composition", coin.composition)
    #toencode = stringBuilder(toencode, "Mass", coin.mass)
    #toencode = stringBuilder(toencode, "Orientation", coin.orientation)
    toencode = stringBuilder(toencode, "", coin.other_notes)
    
    
    qrcode = RQRCode::QRCode.new(toencode)

    image = qrcode.as_png
    return image
  end
  
  def stringBuilder(string, tag, concat)
    if (string == nil)
      string = ""
    end
    
    if (concat != nil && concat.length > 0)
      if (tag != nil && tag.length > 0)
        string = string + tag + ": "
      end
      string = string + concat + ", "
    end
    return string
  end
  
  
  def getvalue(tag, line)
    i = line.index(tag)
    value = nil
    if i != nil
      value = line[i + tag.length, line.length-1].lstrip
    end
    return value
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_coin.html.erb
					<td>
						<div class="panel">
							<% if (coin.date != nil && coin.date.length > 6)%>
								<div class="date label condense">
									<%= coin.date %>
								</div>
							<% else %>
								<div class="date label">
									<%= coin.date %>
								</div>
							<% end %>
							
							
							<%= simple_format(coin.notes, {class: "notes label", wrapper_tag: "div"}) %>
							
							<% if (coin.country != nil && coin.country.length > 14)%>
								<div class="country label condense">
									<%= coin.country %>
								</div>
							<% else %>
								<div class="country label">
									<%= coin.country %>
								</div>
							<% end %>
							<% if (coin.mintage != nil && coin.mintage.length > 0)%>
								<div class="mintage label">m. <%= coin.mintage %></div>
							<% end %>
							
							<% if (coin.denomination != nil && coin.denomination.length > 12)%>
								<div class="denomination label condense">
									<%= coin.denomination %>
								</div>
							<% else %>
								<div class="denomination label">
									<%= coin.denomination %>
								</div>
							<% end %>
							<div class="grade label"><%= coin.grade %></div>
							<% if (coin.condition_notes != nil && coin.condition_notes.length > 0)%>
								<div class="condition label">"<%= coin.condition_notes %>"</div>
							<% end %>
							<div class="catalognumber label"><%= coin.catalog_no %></div>
						</div>
					</td>
					<td>
						<div class="panel">
							
							<img class="qrcode" src="<%= qr.to_data_url %>" />
							<div class="entrydate label">
								<%= Time.now.strftime("%Y-%^b-%d") %>
							</div>
							<% if (coin.composition != nil && coin.composition.length > 18)%>
								<%= simple_format(coin.composition, {class: "composition label condense", wrapper_tag: "div"}) %>
							<% else %>
								<%= simple_format(coin.composition, {class: "composition label", wrapper_tag: "div"}) %>
							<% end %>
							
							
							<div class="diameter label">
								&#x2300; <%= coin.diameter %>
							</div>
							<div class="mass label">
								<%= coin.mass %>
							</div>

						</div>
						
					</td>

app/views/coins/_newcoin.html.erb
<%= form_for coin, html: {class: "pure-form pure-form-aligned"} do |f| %>  
<fieldset>

  <div class="pure-control-group"> 
    <%= f.label "Country" %>
    <%= f.text_field :country %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Denomination" %>
    <%= f.text_field :denomination %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Date" %>
    <%= f.text_field :date %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Notes" %>
    <%= f.text_area :notes %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Mintage" %>
    <%= f.text_field :mintage %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Grade" %>
    <%= f.text_field :grade %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Condition notes" %>
    <%= f.text_area :condition_notes %> 
  </div>
  <div class="pure-control-group"> 
    <%= f.label "Catalog number" %>
    <%= f.text_field :catalog_no %> 
  </div>
 
  
  <div class="pure-control-group"> 
    <%= f.label "Diameter" %> 
    <%= f.text_field :diameter %> 
  </div>
  
  <div class="pure-control-group"> 
    <%= f.label "Composition" %>
    <%= f.text_field :composition %> 
  </div>
  
  <div class="pure-control-group"> 
    <%= f.label "Mass" %> 
    <%= f.text_field :mass %> 
  </div>
  
  <div class="pure-control-group"> 
    <%= f.label "Thickness" %>
    <%= f.text_field :thickness %> 
  </div>
  
  <div class="pure-control-group"> 
    <%= f.label "Shape" %> 
    <%= f.text_field :shape %> 
  </div>

  
  <div class="pure-control-group"> 
    <%= f.label "Orientation" %>
    <%= f.text_field :orientation %> 
  </div>
  
  <div class="pure-control-group"> 
    <%= f.label "Other notes" %>
    <%= f.text_area :other_notes %> 
  </div>
  
  
  
  <div class="pure-controls"> 
    <%= f.submit submitText, :class => 'pure-button pure-button-primary' %> 
  </div> 
  
  </fieldset>
  <% end %>

app/views/coins/edit.html.erb
<div class="layout" >

<h1>Edit Coin Label</h1>

<%= render partial: "newcoin", locals: { coin: @coin, submitText: "Update"} %>

<br>

<table>
<%= render partial: "coin", locals: { coin: @coin, qr: @img} %>
</table>

<br>

	<div class="pure-menu pure-menu-horizontal pure-menu-scrollable">
		<ul class="pure-menu-list">
			 <li class="pure-menu-item"><%= link_to 'Back', coins_path(), { :class=>"pure-menu-link" } %></li>
		</ul>
	</div>

</div>

app/views/coins/index.html.erb
<div class="layout" >
	
	<h1>Coin Labeler</h1>
  
  	<table class="pure-table">
		<tr>
			<th>Country</th>
			<th>Date</th>
			<th>Notes</th>
			<th>Denomination</th>
			<th>Mintage</th>
			<th>Catalog #</th>
			<th>Grade</th>
			<th>Condition</th>
			<th>Extra Notes</th>
			<th>Controls</th>
		</tr>
  	
	    <% @coins.each do |coin| %>
		<tr>
			<td><%= coin.country %></td>
			<td><%= coin.date %></td>
			<td><%= coin.notes %></td>
			<td><%= coin.denomination %></td>
			<td><%= coin.mintage %></td>
			<td><%= coin.catalog_no %></td>
	  		<td><%= coin.grade %></td>
			<td><%= coin.condition_notes %></td>
			<td><%= coin.other_notes %></td>
			<td>
				<%= link_to 'Edit', edit_coin_path(coin), { :class=>"button-success pure-button" } %>
				<%= link_to 'Duplicate', duplicate_coin_path(coin), { :class=>"button-success pure-button" } %>
				<%= link_to 'Delete', delete_coin_path(coin),
				class: "button-error pure-button",
					method: :delete,
		            data: { confirm: 'Are you sure you want to delete this coin?' }%>
			</td>
		</tr>
		<% end %>
		
	   
	
	</table>
	
	<div class="pure-menu pure-menu-horizontal pure-menu-scrollable">
		<ul class="pure-menu-list">
			 <li class="pure-menu-item"><%= link_to 'Add', new_coin_path(), { :class=>"pure-menu-link" } %></li>
			 <li class="pure-menu-item"><%= link_to 'Print', print_coins_path(), { :class=>"pure-menu-link" } %></li>
			 <li class="pure-menu-item"><%= link_to 'Clear All', clear_coins_path(),
			 	class: "pure-menu-link",
			 	method: :delete,
				data: { confirm: 'Are you sure you want to delete all coins?' }%></li>
		</ul>
	</div>

</div>

app/views/coins/new.html.erb
<div class="layout">
<h1>New Coin Label</h1>
<%= form_for @coin, url: fastinput_coin_path(@coin), html: {class: "pure-form pure-form-aligned"} do |f| %>
	<fieldset>
		<div class="pure-control-group"> 
   			<%= f.label "Fast Input" %>
    		<%= f.text_area :fastinput %>
		</div>
	
    <div class="pure-controls"> 
      <%= f.submit "Apply Fast Input", :class => 'pure-button pure-button-primary' %> 
    </div>
  </div>
</fieldset>
<% end %>

<hr>

<%= render partial: "newcoin", locals: { coin: @coin, submitText: "Create"} %>


	<div class="pure-menu pure-menu-horizontal pure-menu-scrollable">
		<ul class="pure-menu-list">
			 <li class="pure-menu-item"><%= link_to 'Back', coins_path(), { :class=>"pure-menu-link" } %></li>
		</ul>
	</div>
</div>

app/views/coins/print.html.erb
<%= stylesheet_link_tag "coindlabelstyle.css" %>

<div class="messages">
  <div class="container">
  
  	<table>
	    <% for index in 0 ... @coins.size %>
		<%	coin = @coins[index] %>
			<% if ((index % 2) == 0) %>
				<tr>
			<% end %>
					<%= render partial: "coin", locals: { coin: coin, qr: @qrcodes[index]} %>
			<% if ((index % 2) == 1) %>
				</tr>
			<% end %>
		<% end %>
		
	   
	
	</table>
	
	
	<!--<%= link_to 'Back', coins_path() %>-->

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoinLabelApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>